[package]
name = "speedrun_parser"
version = "0.1.0"
authors = ["p"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"]}
regex = "1"
chrono = "0.4"
